INSERT INTO [dbo].[CARI_HESAP_HAREKETLERI]
           ([cha_Guid]
           ,[cha_DBCno]
           ,[cha_SpecRecNo]
           ,[cha_iptal]
           ,[cha_fileid]
           ,[cha_hidden]
           ,[cha_kilitli]
           ,[cha_degisti]
           ,[cha_CheckSum]
           ,[cha_create_user]
           ,[cha_create_date]
           ,[cha_lastup_user]
           ,[cha_lastup_date]
           ,[cha_special1]
           ,[cha_special2]
           ,[cha_special3]
           ,[cha_MainProgramNo]
           ,[cha_VersionNo]
           ,[cha_MenuNo]
           ,[cha_MikroSpecial1]
           ,[cha_MikroSpecial2]
           ,[cha_MikroSpecial3]
           ,[cha_ExternalProgramType]
           ,[cha_ExternalProgramId]
           ,[cha_Hash]
           ,[cha_firmano]
           ,[cha_subeno]
           ,[cha_evrak_tip]
           ,[cha_evrakno_seri]
           ,[cha_evrakno_sira]
           ,[cha_satir_no]
           ,[cha_tarihi]
           ,[cha_tip]
           ,[cha_cinsi]
           ,[cha_normal_Iade]
           ,[cha_tpoz]
           ,[cha_ticaret_turu]
           ,[cha_belge_no]
           ,[cha_belge_tarih]
           ,[cha_aciklama]
           ,[cha_satici_kodu]
           ,[cha_EXIMkodu]
           ,[cha_projekodu]
           ,[cha_yat_tes_kodu]
           ,[cha_cari_cins]
           ,[cha_kod]
           ,[cha_ciro_cari_kodu]
           ,[cha_d_cins]
           ,[cha_d_kur]
           ,[cha_altd_kur]
           ,[cha_grupno]
           ,[cha_srmrkkodu]
           ,[cha_kasa_hizmet]
           ,[cha_kasa_hizkod]
           ,[cha_karsidcinsi]
           ,[cha_karsid_kur]
           ,[cha_karsidgrupno]
           ,[cha_karsisrmrkkodu]
           ,[cha_miktari]
           ,[cha_birimfiyat]
           ,[cha_meblag]
           ,[cha_aratoplam]
           ,[cha_vade]
           ,[cha_Vade_Farki_Yuz]
           ,[cha_ft_iskonto1]
           ,[cha_ft_iskonto2]
           ,[cha_ft_iskonto3]
           ,[cha_ft_iskonto4]
           ,[cha_ft_iskonto5]
           ,[cha_ft_iskonto6]
           ,[cha_ft_masraf1]
           ,[cha_ft_masraf2]
           ,[cha_ft_masraf3]
           ,[cha_ft_masraf4]
           ,[cha_isk_mas1]
           ,[cha_isk_mas2]
           ,[cha_isk_mas3]
           ,[cha_isk_mas4]
           ,[cha_isk_mas5]
           ,[cha_isk_mas6]
           ,[cha_isk_mas7]
           ,[cha_isk_mas8]
           ,[cha_isk_mas9]
           ,[cha_isk_mas10]
           ,[cha_sat_iskmas1]
           ,[cha_sat_iskmas2]
           ,[cha_sat_iskmas3]
           ,[cha_sat_iskmas4]
           ,[cha_sat_iskmas5]
           ,[cha_sat_iskmas6]
           ,[cha_sat_iskmas7]
           ,[cha_sat_iskmas8]
           ,[cha_sat_iskmas9]
           ,[cha_sat_iskmas10]
           ,[cha_yuvarlama]
           ,[cha_StFonPntr]
           ,[cha_stopaj]
           ,[cha_savsandesfonu]
           ,[cha_avansmak_damgapul]
           ,[cha_vergipntr]
           ,[cha_vergisiz_fl]
           ,[cha_otvtutari]
           ,[cha_otvvergisiz_fl]
           ,[cha_oiv_pntr]
           ,[cha_oivtutari]
           ,[cha_oiv_vergi]
           ,[cha_oivergisiz_fl]
           ,[cha_fis_tarih]
           ,[cha_fis_sirano]
           ,[cha_trefno]
           ,[cha_sntck_poz]
           ,[cha_reftarihi]
           ,[cha_istisnakodu]
           ,[cha_pos_hareketi]
           ,[cha_meblag_ana_doviz_icin_gecersiz_fl]
           ,[cha_meblag_alt_doviz_icin_gecersiz_fl]
           ,[cha_meblag_orj_doviz_icin_gecersiz_fl]
           ,[cha_sip_uid]
           ,[cha_kirahar_uid]
           ,[cha_vardiya_tarihi]
           ,[cha_vardiya_no]
           ,[cha_vardiya_evrak_ti]
           ,[cha_ebelge_turu]
           ,[cha_tevkifat_toplam]
           ,[cha_e_islem_turu]
           ,[cha_fatura_belge_turu]
           ,[cha_diger_belge_adi]
           ,[cha_uuid]
           ,[cha_adres_no]
           ,[cha_vergifon_toplam]
           ,[cha_ilk_belge_tarihi]
           ,[cha_ilk_belge_doviz_kuru]
           ,[cha_HareketGrupKodu1]
           ,[cha_HareketGrupKodu2]
           ,[cha_HareketGrupKodu3]
           ,[cha_ebelgeno_seri]
           ,[cha_ebelgeno_sira]
           ,[cha_hubid]
           ,[cha_hubglbid]
           ,[cha_bsba_e_belge_mi]
           ,[cha_eticaret_kanal_kodu]
           ,[cha_hizli_satis_kasa_no]
           ,[cha_ebelge_Islemturu]
           ,[cha_tevkifat_sifirlandi_fl]
           ,[cha_vergi1]
           ,[cha_vergi2]
           ,[cha_vergi3]
           ,[cha_vergi4]
           ,[cha_vergi5]
           ,[cha_vergi6]
           ,[cha_vergi7]
           ,[cha_vergi8]
           ,[cha_vergi9]
           ,[cha_vergi10]
           ,[cha_vergi11]
           ,[cha_vergi12]
           ,[cha_vergi13]
           ,[cha_vergi14]
           ,[cha_vergi15]
           ,[cha_vergi16]
           ,[cha_vergi17]
           ,[cha_vergi18]
           ,[cha_vergi19]
           ,[cha_vergi20]
           ,[cha_ilave_edilecek_kdv1]
           ,[cha_ilave_edilecek_kdv2]
           ,[cha_ilave_edilecek_kdv3]
           ,[cha_ilave_edilecek_kdv4]
           ,[cha_ilave_edilecek_kdv5]
           ,[cha_ilave_edilecek_kdv6]
           ,[cha_ilave_edilecek_kdv7]
           ,[cha_ilave_edilecek_kdv8]
           ,[cha_ilave_edilecek_kdv9]
           ,[cha_ilave_edilecek_kdv10]
           ,[cha_ilave_edilecek_kdv11]
           ,[cha_ilave_edilecek_kdv12]
           ,[cha_ilave_edilecek_kdv13]
           ,[cha_ilave_edilecek_kdv14]
           ,[cha_ilave_edilecek_kdv15]
           ,[cha_ilave_edilecek_kdv16]
           ,[cha_ilave_edilecek_kdv17]
           ,[cha_ilave_edilecek_kdv18]
           ,[cha_ilave_edilecek_kdv19]
           ,[cha_ilave_edilecek_kdv20]
           ,[cha_efatura_belge_tipi])
     VALUES
           (NEWID()
           ,0
           ,0
           ,0
           ,51
           ,0
           ,0
           ,0
           ,0
           ,1
           ,GETDATE()
           ,1
           ,GETDATE()
           ,N''
           ,N''
           ,N''
           ,0
           ,N''
           ,N''
           ,N''
           ,N''
           ,N''
           ,0
           ,N''
           ,0
           ,0
           ,0
           ,0								--cha_evrak_tip
           ,N'EFLMSRF'						--cha_evrakno_seri
           ,(SELECT TOP 1 cha_evrakno_sira+1 FROM CARI_HESAP_HAREKETLERI ORDER by cha_evrakno_sira DESC)--cha_evrakno_sira
           ,1								--cha_satir_no
           ,%kayit_tarihi%					--cha_tarihi
           ,1								--cha_tip
           ,8								--cha_cinsi
           ,0
           ,0
           ,0
           ,%gib_no%--cha_belge_no
           ,%kayit_tarihi%--cha_belge_tarih
           %mikro_aciklama%,--cha_aciklama
           ,N''
           ,N''
           %proje_kodu%,--cha_projekodu
           ,N''
           ,0
           %cari_kod%,--cha_kod
           %cari_kod%,--cha_ciro_cari_kodu
           ,0
           ,1
           ,34,09
           ,0
           ,%sorumluluk_merkezi%--cha_srmrkkodu
           ,5
           ,%masrafkodu%--cha_kasa_hizkod
           ,0
           ,1
           ,0
           ,%sorumluluk_merkezi%--cha_karsisrmrkkodu
           ,1
           ,0
           %taxinclusiveamount%,
           %taxexclusiveamount%,
           DATEADD(DAY, 30, GETDATE()),--cha_vade
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,8										--cha_vergipntr
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,GETDATE()										--cha_fis_tarih
           ,(SELECT TOP 1 cha_fis_sirano+1 FROM CARI_HESAP_HAREKETLERI ORDER by cha_fis_sirano DESC)										--cha_fis_sirano
           ,N''
           ,0
           ,N'1899-12-30 00:00:00.000'
           ,0
           ,0
           ,0
           ,0
           ,0
           ,N'00000000-0000-0000-0000-000000000000'
           ,N'00000000-0000-0000-0000-000000000000'
           ,N'1899-12-30 00:00:00.000'
           ,0
           ,0
           ,1
           ,0
           ,1
           ,0
           ,N''
           ,N'00000000-0000-0000-0000-000000000000'
           ,1
           ,0
           ,N'1899-12-30 00:00:00.000'
           ,0
           ,N''
           ,N''
           ,N''
           ,N''
           ,0
           ,N''
           ,N''
           ,1
           ,N''
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
           ,0
		   )



