INSERT INTO [dbo].[PERSONEL_IZINLERI]
           ([pz_Guid]
           ,[pz_DBCno]
           ,[pz_SpecRECno]
           ,[pz_iptal]
           ,[pz_fileid]
           ,[pz_hidden]
           ,[pz_kilitli]
           ,[pz_degisti]
           ,[pz_checksum]
           ,[pz_create_user]
           ,[pz_create_date]
           ,[pz_lastup_user]
           ,[pz_lastup_date]
           ,[pz_izin_yil]
           ,[pz_pers_kod]
           ,[pz_izin_no]
           ,[pz_izin_tipi]
           ,[pz_gun_sayisi]
           ,[pz_yol_izni]
           ,[pz_baslangictarih]
           ,[pz_bagli_talep_uid]
           ,[pz_izin_aciklama]
           ,[pz_gerceklesen_donus_tarihi]
           ,[pz_izin_detay_tipi]
           ,[pz_bitistarihi]
           ,[pz_isbasitarihi]
           ,[pz_saat]
           ,[pz_BaslamaSaati]
           ,[pz_eksikcalismanedeni])
     VALUES
           (
            NEWID()
           ,0
           ,0
           ,0
           ,100
           ,0
           ,0
           ,0
           ,0
           ,1
           ,GETDATE()
           ,1
           ,GETDATE()
           ,YEAR(GETDATE())
           ,%specode5%
           ,%izin_no%
           ,%izin_tipi%
           ,%gun_sayisi%
           ,%yol_izni%
           ,%izin_baslangic_tarihi%
           ,'00000000-0000-0000-0000-000000000000'
           ,%izin_aciklamasi%
           ,%izin_bitis_tarihi%
           ,%izin_detay_tipi%
           ,%izin_bitis_tarihi%
           ,DATEADD(DAY, 1, %izin_bitis_tarihi%)
           ,0
           ,%izin_baslangic_tarihi%
           ,%eksik_calisma_nedeni%
)
