INSERT INTO {vt}.dbo.CARI_HESAP_HAREKETLERI 
(
cha_Guid, cha_DBCno, cha_SpecRecNo, cha_iptal, cha_fileid,
    cha_hidden, cha_kilitli, cha_degisti, cha_CheckSum,
    cha_create_user, cha_create_date, cha_lastup_user, cha_lastup_date,
    cha_special1, cha_special2, cha_special3,
    cha_firmano, cha_subeno, cha_evrak_tip,
    cha_evrakno_seri, cha_evrakno_sira, cha_satir_no,
    cha_tarihi, cha_tip, cha_cinsi,
    cha_belge_no, cha_belge_tarih, cha_aciklama,
    cha_kod, cha_ciro_cari_kodu, cha_d_kur,
    cha_altd_kur, cha_kasa_hizmet, cha_kasa_hizkod,
    cha_miktari, cha_meblag, cha_aratoplam,
    cha_fis_tarih, cha_fis_sirano, cha_uuid
)
VALUES (
    NEWID(),
    0,
    0,
    0,
    51,
    0,
    0,
    0,
    0,
    1,
    GETDATE(),
    1,
    GETDATE(),
    '',
    '',
    '',
    0,
    0,
    0,
    'EFLMSRF',
    %sira%,
    0,
    GETDATE(),
    1,
    8,
    '',
    GETDATE(),
    'Eflow Masraf Kaydi',
    %cari_kod%,
    %cari_kod%,
    1.0000,
    18.7946,
    5,
    %masrafkodu%,
    1,
    %taxinclusiveamount%,
    %taxexclusiveamount%,
    GETDATE(),
    1,
    NEWID()
);
