INSERT INTO [dbo].[MUHASEBE_FISLERI]
           ([fis_Guid]
           ,[fis_DBCno]
           ,[fis_SpecRECno]
           ,[fis_iptal]
           ,[fis_fileid]
           ,[fis_hidden]
           ,[fis_kilitli]
           ,[fis_degisti]
           ,[fis_checksum]
           ,[fis_create_user]
           ,[fis_create_date]
           ,[fis_lastup_user]
           ,[fis_lastup_date]
           ,[fis_special1]
           ,[fis_special2]
           ,[fis_special3]
           ,[fis_MainProgramNo]
           ,[fis_VersionNo]
           ,[fis_MenuNo]
           ,[fis_MikroSpecial1]
           ,[fis_MikroSpecial2]
           ,[fis_MikroSpecial3]
           ,[fis_ExternalProgramType]
           ,[fis_ExternalProgramId]
           ,[fis_Hash]
           ,[fis_firmano]
           ,[fis_subeno]
           ,[fis_maliyil]
           ,[fis_tarih]
           ,[fis_sira_no]
           ,[fis_tur]
           ,[fis_hesap_kod]
           ,[fis_satir_no]
           ,[fis_aciklama1]
           ,[fis_meblag0]
           ,[fis_meblag1]
           ,[fis_meblag2]
           ,[fis_meblag3]
           ,[fis_meblag4]
           ,[fis_meblag5]
           ,[fis_meblag6]
           ,[fis_sorumluluk_kodu]
           ,[fis_ticari_tip]
           ,[fis_ticari_uid]
           ,[fis_kurfarkifl]
           ,[fis_ticari_evraktip]
           ,[fis_tic_evrak_seri]
           ,[fis_tic_evrak_sira]
           ,[fis_tic_belgeno]
           ,[fis_tic_belgetarihi]
           ,[fis_yevmiye_no]
           ,[fis_katagori]
           ,[fis_evrak_DBCno]
           ,[fis_fmahsup_tipi]
           ,[fis_fozelmahkod]
           ,[fis_grupkodu]
           ,[fis_aktif_pasif]
           ,[fis_proje_kodu]
           ,[fis_HareketGrupKodu1]
           ,[fis_HareketGrupKodu2]
           ,[fis_HareketGrupKodu3]
           ,[fis_ticari_hubid]
           ,[fis_ticari_hubglbid])
     VALUES
           (
		   NEWID()
           ,0
           ,0
           ,0
           ,2
           ,0
           ,0
           ,0
           ,0
           ,1
           ,GETDATE()
           ,1
           ,GETDATE()
           ,N''
           ,N''
           ,N''
           ,0
           ,N''
           ,N''
           ,N''
           ,N''
           ,N''
           ,0
           ,N''
           ,0
           ,0
           ,0
           ,YEAR(GETDATE())
           ,%kayit_tarihi%
           ,(SELECT TOP 1 fis_sira_no+1 FROM MUHASEBE_FISLERI ORDER BY fis_sira_no DESC)
           ,0
           ,<fis_hesap_kod, nvarchar(25),>
           ,1
           ,<fis_aciklama1, nvarchar(127),>
           ,%taxexclusiveamount%
           ,%taxexclusiveamount%
           ,%taxexclusiveamount%
           ,0
           ,0
           ,0
           ,0
           ,%sorumluluk_kodu%
           ,2
           ,N'00000000-0000-0000-0000-000000000000'
           ,0
           ,63
           ,N'EFLMSRF'
           ,(SELECT TOP 1 cha_evrakno_sira FROM CARI_HESAP_HAREKETLERI
ORDER by cha_evrakno_sira DESC)
           ,%gib_no%
           ,%kayit_tarihi%
           ,(SELECT TOP 1 fis_yevmiye_no+1 FROM MUHASEBE_FISLERI ORDER BY fis_yevmiye_no DESC)
           ,0
           ,0
           ,0
           ,N''
           ,N''
           ,0
           ,%proje_kodu%
           ,N''
           ,N''
           ,N''
           ,N''
           ,N'')

