INSERT INTO {vt}.dbo.SIPARISLER
           ([sip_Guid]
           ,[sip_DBCno]
           ,[sip_SpecRECno]
           ,[sip_iptal]
           ,[sip_fileid]
           ,[sip_hidden]
           ,[sip_kilitli]
           ,[sip_degisti]
           ,[sip_checksum]
           ,[sip_create_user]
           ,[sip_create_date]
           ,[sip_lastup_user]
           ,[sip_lastup_date]
           ,[sip_special1]
           ,[sip_special2]
           ,[sip_special3]
           ,[sip_firmano]
           ,[sip_subeno]
           ,[sip_tarih]
           ,[sip_teslim_tarih]
           ,[sip_tip]
           ,[sip_cins]
           ,[sip_evrakno_seri]
           ,[sip_evrakno_sira]
           ,[sip_satirno]
           ,[sip_belgeno]
           ,[sip_belge_tarih]
           ,[sip_satici_kod]
           ,[sip_musteri_kod]
           ,[sip_stok_kod]
           ,[sip_b_fiyat]
           ,[sip_miktar]
           ,[sip_birim_pntr]
           ,[sip_teslim_miktar]
           ,[sip_tutar]
           ,[sip_iskonto_1]
           ,[sip_iskonto_2]
           ,[sip_iskonto_3]
           ,[sip_iskonto_4]
           ,[sip_iskonto_5]
           ,[sip_iskonto_6]
           ,[sip_masraf_1]
           ,[sip_masraf_2]
           ,[sip_masraf_3]
           ,[sip_masraf_4]
           ,[sip_vergi_pntr]
           ,[sip_vergi]
           ,[sip_masvergi_pntr]
           ,[sip_masvergi]
           ,[sip_opno]
           ,[sip_aciklama]
           ,[sip_aciklama2]
           ,[sip_depono]
           ,[sip_OnaylayanKulNo]
           ,[sip_vergisiz_fl]
           ,[sip_kapat_fl]
           ,[sip_promosyon_fl]
           ,[sip_cari_sormerk]
           ,[sip_stok_sormerk]
           ,[sip_cari_grupno]
           ,[sip_doviz_cinsi]
           ,[sip_doviz_kuru]
           ,[sip_alt_doviz_kuru]
           ,[sip_adresno]
           ,[sip_teslimturu]
           ,[sip_cagrilabilir_fl]
           ,[sip_prosip_uid]
           ,[sip_iskonto1]
           ,[sip_iskonto2]
           ,[sip_iskonto3]
           ,[sip_iskonto4]
           ,[sip_iskonto5]
           ,[sip_iskonto6]
           ,[sip_masraf1]
           ,[sip_masraf2]
           ,[sip_masraf3]
           ,[sip_masraf4]
           ,[sip_isk1]
           ,[sip_isk2]
           ,[sip_isk3]
           ,[sip_isk4]
           ,[sip_isk5]
           ,[sip_isk6]
           ,[sip_mas1]
           ,[sip_mas2]
           ,[sip_mas3]
           ,[sip_mas4]
           ,[sip_Exp_Imp_Kodu]
           ,[sip_kar_orani]
           ,[sip_durumu]
           ,[sip_stal_uid]
           ,[sip_planlananmiktar]
           ,[sip_teklif_uid]
           ,[sip_parti_kodu]
           ,[sip_lot_no]
           ,[sip_projekodu]
           ,[sip_fiyat_liste_no]
           ,[sip_Otv_Pntr]
           ,[sip_Otv_Vergi]
           ,[sip_otvtutari]
           ,[sip_OtvVergisiz_Fl]
           ,[sip_paket_kod]
           ,[sip_Rez_uid]
           ,[sip_harekettipi]
           ,[sip_yetkili_uid]
           ,[sip_kapatmanedenkod]
           ,[sip_gecerlilik_tarihi]
           ,[sip_onodeme_evrak_tip]
           ,[sip_onodeme_evrak_seri]
           ,[sip_onodeme_evrak_sira]
           ,[sip_rezervasyon_miktari]
           ,[sip_rezerveden_teslim_edilen]
           ,[sip_HareketGrupKodu1]
           ,[sip_HareketGrupKodu2]
           ,[sip_HareketGrupKodu3]
           ,[sip_Olcu1]
           ,[sip_Olcu2]
           ,[sip_Olcu3]
           ,[sip_Olcu4]
           ,[sip_Olcu5]
           ,[sip_FormulMiktarNo]
           ,[sip_FormulMiktar]
           ,[sip_satis_fiyat_doviz_cinsi]
           ,[sip_satis_fiyat_doviz_kuru]
           ,[sip_eticaret_kanal_kodu]
           ,[sip_Tevkifat_turu]
           ,[sip_otv_tevkifat_turu]
           ,[sip_otv_tevkifat_tutari]
           ,[sip_tevkifat_sifirlandi_fl])
(SELECT
   NEWID(),                   -- [sip_Guid]
   0,                         -- [sip_DBCno]
   0,                         -- [sip_SpecRECno]
   0,                         -- [sip_iptal]
   21,                        -- [sip_fileid]
   0,                         -- [sip_hidden]
   0,                         -- [sip_kilitli]
   0,                         -- [sip_degisti]
   0,                         -- [sip_checksum]
   1,                         -- [sip_create_user]
   GETDATE(),                 -- [sip_create_date]
   1,                         -- [sip_lastup_user]
   GETDATE(),                 -- [sip_lastup_date]
   N'',                       -- [sip_special1]
   N'',                       -- [sip_special2]
   N'',                       -- [sip_special3]
   0,                         -- [sip_firmano]
   0,                         -- [sip_subeno]
   GETDATE(),                 -- [sip_tarih]
   GETDATE(),                 -- [sip_teslim_tarih]
   1,                         -- [sip_tip]
   0,                         -- [sip_cins]
   N'GDK',                    -- [sip_evrakno_seri]
   %sira%, -- [sip_evrakno_sira]
   ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) + 1,                         -- [sip_satirno]
   N'GDK',               -- [sip_belgeno]
   GETDATE(),                 -- [sip_belge_tarih]
   N'',                       -- [sip_satici_kod]
   dt.Firma,                -- [sip_musteri_kod]
   dt.Aciklama,                -- [sip_stok_kod]
   0, -- [sip_b_fiyat]
   dt.Miktar, -- [sip_miktar]
   0,                         -- [sip_birim_pntr]
   0,                         -- [sip_teslim_miktar]
   dt.ToplamFiyat, -- [sip_tutar]
   0, 0, 0, 0, 0, 0,          -- [sip_iskonto_1] ... [sip_iskonto_6]
 0, 0, 0, 0,                -- [sip_masraf_1] ... [sip_masraf_4]
   0,                         -- [sip_vergi_pntr]
   0,                         -- [sip_vergi]
   0,                         -- [sip_masvergi_pntr]
   0,                         -- [sip_masvergi]
   0,                         -- [sip_opno]
   N'',                       -- [sip_aciklama]
   N'',                       -- [sip_aciklama2]
   0,                         -- [sip_depono]
   0,                         -- [sip_OnaylayanKulNo]
   0,                         -- [sip_vergisiz_fl]
   0,                         -- [sip_kapat_fl]
   0,                         -- [sip_promosyon_fl]
   N'GENEL YÖNETİM',          -- [sip_cari_sormerk]
   N'GENEL YÖNETİM',          -- [sip_stok_sormerk]
   0,                         -- [sip_cari_grupno]
   0,                         -- [sip_doviz_cinsi]
   0,                         -- [sip_doviz_kuru]
   0,                         -- [sip_alt_doviz_kuru]
   0,                         -- [sip_adresno]
   N'',                       -- [sip_teslimturu]
   0,                         -- [sip_cagrilabilir_fl]
   NEWID(),                   -- [sip_prosip_uid]
   0, 0, 0, 0, 0, 0,          -- [sip_iskonto1] ... [sip_iskonto6]
   0, 0, 0, 0,                -- [sip_masraf1] ... [sip_masraf4]
   0,                         -- [sip_isk1]
   0,                         -- [sip_isk2]
   0,                         -- [sip_isk3]
   0,                         -- [sip_isk4]
   0,                         -- [sip_isk5]
   0,                         -- [sip_isk6]
   0,                         -- [sip_mas1]
   0,                         -- [sip_mas2]
   0,                         -- [sip_mas3]
   0,                         -- [sip_mas4]
   N'',                       -- [sip_Exp_Imp_Kodu]
   0,                         -- [sip_kar_orani]
   0,                         -- [sip_durumu]
   NEWID(),                   -- [sip_stal_uid]
   0,                         -- [sip_planlananmiktar]
   NEWID(),                   -- [sip_teklif_uid]
   N'',                       -- [sip_parti_kodu]
   0,                         -- [sip_lot_no]
   N'',                       -- [sip_projekodu]
   0,                         -- [sip_fiyat_liste_no]
   0,                         -- [sip_Otv_Pntr]
   0,                         -- [sip_Otv_Vergi]
   0,                         -- [sip_otvtutari]
   0,                         -- [sip_OtvVergisiz_Fl]
   N'',                       -- [sip_paket_kod]
   NEWID(),                   -- [sip_Rez_uid]
   0,                         -- [sip_harekettipi]
   NEWID(),                   -- [sip_yetkili_uid]
   N'',                       -- [sip_kapatmanedenkod]
   GETDATE(),                 -- [sip_gecerlilik_tarihi]
   0,                         -- [sip_onodeme_evrak_tip]
   N'',                       -- [sip_onodeme_evrak_seri]
   0,                         -- [sip_onodeme_evrak_sira]
   0,                         -- [sip_rezervasyon_miktari]
   0,                         -- [sip_rezerveden_teslim_edilen]
   N'',                       -- [sip_HareketGrupKodu1]
   N'',                       -- [sip_HareketGrupKodu2]
   N'',                       -- [sip_HareketGrupKodu3]
   0,                         -- [sip_Olcu1]
   0,                         -- [sip_Olcu2]
   0,                         -- [sip_Olcu3]
   0,                         -- [sip_Olcu4]
   0,                         -- [sip_Olcu5]
   0,                         -- [sip_FormulMiktarNo]
   0,                         -- [sip_FormulMiktar]
   0,                         -- [sip_satis_fiyat_doviz_cinsi]
   0,                         -- [sip_satis_fiyat_doviz_kuru]
   N'',                       -- [sip_eticaret_kanal_kodu]
   0,                         -- [sip_Tevkifat_turu]
   0,                         -- [sip_otv_tevkifat_turu]
   0,                         -- [sip_otv_tevkifat_tutari]
   0                          -- [sip_tevkifat_sifirlandi_fl]
FROM (
SELECT
	    x.Rec.value('./ColumnData[1]', 'bit') AS Aktif,
        x.Rec.value('./ColumnData[2]', 'NVARCHAR(MAX)') AS Aciklama,
        x.Rec.value('./ColumnData[3]', 'NVARCHAR(MAX)') AS Ozellik,
        x.Rec.value('./ColumnData[4]', 'int') AS Miktar,
        x.Rec.value('./ColumnData[5]', 'NVARCHAR(MAX)') AS Birim,
        x.Rec.value('./ColumnData[7]', 'FLOAT') AS ToplamFiyat,
		x.Rec.value('./ColumnData[8]', 'NVARCHAR(MAX)') AS Firma,
        x.Rec.value('./ColumnData[9]', 'NVARCHAR(MAX)') AS FirmaBilgileri
        
    FROM (
        SELECT CAST(VALUE AS XML) AS xdt, CIID 
        FROM EFLOW.DBO.INST_DATA_MEMO 
        WHERE DID = 10732 AND CIID = %surec_id%
    ) e
    CROSS APPLY e.xdt.nodes('/LineItemTable/TableData/Data') AS x(Rec)
	where  x.Rec.value('./ColumnData[1]', 'bit')=1
) dt)
