INSERT INTO MikroDB_V16_MRP2.dbo.ZIMMET_HAREKETLERI 
(
    zmh_Guid, 
    zmh_DBCno, 
    zmh_SpecRECno,  
    zmh_iptal,  
    zmh_fileid,  
    zmh_hidden,
    zmh_kilitli,
    zmh_degisti,
    zmh_checksum,
    zmh_create_user,
    zmh_create_date,
    zmh_lastup_user,
    zmh_lastup_date,
    zmh_special1,
    zmh_special2,
    zmh_special3,
    zmh_firmano, 
    zmh_subeno, 
    zmh_tarihi, 
    zmh_evrakno_seri, 
    zmh_evrakno_sira, 
    zmh_satirno, 
    zmh_belgeno, 
    zmh_belge_tarihi, 
    zmh_demirbas_kodu, 
    zmh_zimmet_alan_per_kodu, 
    zmh_zimmet_veren_per_kodu, 
    zmh_cikis_zimmet_yeri,
    zmh_giris_zimmet_yeri, 
    zmh_miktar, 
    zmh_zimmetten_dusme_tarihi, 
    zmh_durumu, 
    zmh_aciklama,
    zmh_satir_aciklama,
    zmh_sorumluluk_merkezi,
    zmh_proje_kodu
) 
SELECT
    NEWID(),
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    N'',
    GETDATE(),
    N'',
    GETDATE(),
    N'',
    N'',
    N'',
    0,
    0,
    GETDATE(),
    N'',
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)),
    0,
    N'',
    GETDATE(),
    dt.Demirbaskodu,
    dt.Zimmetalan,
    dt.Zimmetveren,
    0,
    0,
    dt.Miktar,
    GETDATE(),
    dt.Durum, 
    dt.Aciklama,
    N'',
    dt.Sorumlulukmerkezi,
    dt.Proje
FROM (
    SELECT 
        x.Rec.query('./ColumnData[1]').value('.', 'NVARCHAR(MAX)') AS Zimmetgiris,
        x.Rec.query('./ColumnData[2]').value('.', 'NVARCHAR(MAX)') AS Zimmetalan,
        x.Rec.query('./ColumnData[3]').value('.', 'NVARCHAR(MAX)') AS Zimmetveren,
        x.Rec.query('./ColumnData[4]').value('.', 'NVARCHAR(MAX)') AS Demirbaskodu,
        x.Rec.query('./ColumnData[5]').value('.', 'float') AS FileID,
        x.Rec.query('./ColumnData[6]').value('.', 'Date') AS Tarih,
        x.Rec.query('./ColumnData[7]').value('.', 'float') AS Miktar,
        x.Rec.query('./ColumnData[8]').value('.', 'NVARCHAR(MAX)') AS Durum,
        x.Rec.query('./ColumnData[9]').value('.', 'NVARCHAR(MAX)') AS Sorumlulukmerkezi,
        x.Rec.query('./ColumnData[10]').value('.', 'NVARCHAR(MAX)') AS Proje,
        x.Rec.query('./ColumnData[11]').value('.', 'NVARCHAR(MAX)') AS Aciklama
    FROM  
    (
        SELECT cast(VALUE as XML) as xdt 
        FROM EFLOW.DBO.INST_DATA_MEMO
        WHERE DID=10925 AND CIID=%surec_id%
    ) e
    CROSS APPLY e.xdt.nodes('/LineItemTable/TableData/Data') as x(Rec)
) dt;
